apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-kafka-consumer
 namespace: hpa-default
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: kafka-consumer-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50